### ISSUE TITLE
Allow frames to start at values other than zero during dataset generation

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/colorizer-data#19]
Currently, the `write_manifest` utility method takes in a number of frames, and writes the assumed frame numbers starting at 0. (`frame_0.png`, then `frame_1.png`, `frame_2.png`, etc. )

However, some datasets start at later timepoints, which can cause the dataset manifest to expect frame numbers that don't exist. Trying to load these datasets in the UI leads to errors.

We can't just store these values on calls to `write_image`, since it can be called in multiprocessing contexts where we can't save values to internal state.

Easy fix:
- Add an optional variable `start_frame` to `write_manifest` that offsets the written frame numbers.

Hard (but more robust) version:
- Update `write_data` to take an argument for frames, and allow users to pass in a list of string frame names.
  - This gives the most freedom in case users need to skip frames numbers or something in the future. It also allows users to repeat frames (like an empty frame).
  - Should the frame numbers be stored as an object? How should we handle non-contiguous frames? Is there ever a case where that should be allowed?
- Also add a utility method that generates frame numbers with a number of frames + starting frame number. This should be used in almost all cases.

See also https://github.com/allen-cell-animated/nucmorph-colorizer/issues/203.

**Comment by toloudis** [comment]
Is there a current use case for the "hard" version?

**Comment by ShrimpCryptid** [comment]
I asked Goutham and he said there wasn't *currently* a use case where it exists, but it's possible that it might come up in the future? As I noted the harder version seems a bit more robust, and it lets me also pull out and document some of the hidden behavior in `write_manifest` that currently exists.

**Comment by ShrimpCryptid** [comment]
> Is there a current use case for the "hard" version?

Also, if someone wants to copy an existing group images, or wants to use a different naming convention, letting users define their own arrays of frame paths enables that.
